### ISSUE TITLE
Timeline for code release

### ISSUE THREAD

**Issue by aykutfirat** [jxhe/struct-learning-with-flow#1]
Hi,

Thanks for the great work. Is there a timeline for code release? 

Thanks!

**Comment by jxhe** [comment]
Thanks for your interest ! The code will be released around end of September.

**Comment by jiqiujia** [comment]
Now is October. When will the code be released?

**Comment by jxhe** [comment]
Sorry it is a bit behind schedule, but I start working on this today and should release it soon.

**Comment by jxhe** [comment]
Thanks for your interest, and the full code is available now.
