### ISSUE TITLE
Question about HMM tagger

### ISSUE THREAD

**Issue by speedcell4** [jxhe/struct-learning-with-flow#5]
Hi, could you please explain why do you need to normalize the transition matrix here? Thanks~

https://github.com/jxhe/struct-learning-with-flow/blob/282d547a912598360cffe448304d8c281879bcfd/modules/markov_flow_model.py#L213-L216

**Comment by jxhe** [comment]
Because transition matrix is a probability matrix and should be normalized?

**Comment by speedcell4** [comment]
Sorry for this stupid question, I thought it as CRF
