### ISSUE TITLE
DMV without gold POS

### ISSUE THREAD

**Issue by lephong** [jxhe/struct-learning-with-flow#6]
I noticed that dmv_flow is initialized with dmv_viterbi. However, the latter is trained on (gold) POS. Thus, I suspect that dmv_flow is not completely POS-free. If I am right, I wonder how to replicate the unsupervised dependency parsing results in the paper (which says that "While, traditionally, DMV is trained using gold POS tags as observed syntactic categories, in our approach, we treat each tag as a latent variable").

**Comment by jxhe** [comment]
Hi, in experiments we replaced the TAG column in the training file with POS tags predicted from our HMM unsupervised tagger, for both dmv_viterbi and dmv_flow. Feel free to send me email if you want the training file we used for dmv_flow, or you can try obtaining unsupervised tags from the HMM tags first.

**Comment by lephong** [comment]
I got it. It makes sense now. Many thanks!
